#!/bin/bash

# Cleanup
rm -r ./tools &> /dev/null

# Build the tools
echo "Compiling font generator for linux"
dotnet publish -c Release -r linux-x64 -o ./tools/linux-x64/fontgenerator --nologo --self-contained --force -v q ./src/Arqanore.FontGenerator/*.csproj

echo "Compiling font generator for windows"
dotnet publish -c Release -r win-x64 -o ./tools/win-x64/fontgenerator --nologo --self-contained --force -v q ./src/Arqanore.FontGenerator/*.csproj

echo "Compiling tex generator for linux"
dotnet publish -c Release -r linux-x64 -o ./tools/linux-x64/texgenerator --nologo --self-contained --force -v q ./src/Arqanore.TexGenerator/*.csproj

echo "Compiling tex generator for windows"
dotnet publish -c Release -r win-x64 -o ./tools/win-x64/texgenerator --nologo --self-contained --force -v q ./src/Arqanore.TexGenerator/*.csproj
