#!/bin/bash

# Generate folders
mkdir "lib"
mkdir "tools"

# Clone the TilarGL library
cd "lib"
git clone git@github.com:TheBoneJarmer/TilarGL.git

# Prepare the library
cd "TilarGL"
./init
./generate

# Build the linux version and copy the output to the lib folder
dotnet publish -c Release -r linux-x64 -o temp ./src-tilargl/linux/TilarGL.csproj
cd ..
cp ./TilarGL/temp/TilarGL.dll .

# Remove the folder and cd back to the repo root
rm -rf TilarGL
cd "..";

# Generate tools
dotnet publish -c Release -r linux-x64 -o tools /p:PublishSingleFile=true ./src-tools/fontgenerator/FontGenerator.csproj
dotnet publish -c Release -r linux-x64 -o tools /p:PublishSingleFile=true ./src-tools/fontviewer/FontViewer.csproj
