#!/bin/bash

rm -r "bin" &> /dev/null

dotnet publish -c Release -r linux-x64 -o bin /p:PublishSingleFile=true ./src-tools/fontgenerator/FontGenerator.csproj
dotnet publish -c Release -r linux-x64 -o bin /p:PublishSingleFile=true ./src-tools/fontviewer/FontViewer.csproj
