#!/bin/bash

BRANCH="`git branch --show-current`"

rm -r out/ &> /dev/null
dotnet publish -c Release -r linux-x64 -o out/fontgenerator/ src/Arqanore.FontGenerator/*.csproj
dotnet publish -c Release -r linux-x64 -o out/texgenerator/ src/Arqanore.TexGenerator/*.csproj
dotnet pack -c Release -o out/ src/Arqanore/*.csproj

if [ $BRANCH = "main" ]
then
	dotnet nuget push out/*.nupkg -s nuget.org -k $NUGET_API_KEY
else
	dotnet nuget push out/*.nupkg -s github
fi
