#!/bin/bash

branch=`git branch --show-current`

rm *.nupkg
dotnet pack -c Release -o . ./src/Arqanore/*.csproj

if [ $branch = "develop" ]
then
	dotnet nuget push -s github *.nupkg
	exit
fi

if [ $branch = "main" ]
then
	dotnet nuget push -s nuget.org -k $NUGET_API_KEY *.nupkg
	exit
fi

echo "Can only publish on branch develop or main"
exit 1
